#!/bin/sh

down() {
brightnessctl set 5%-
b=`brightnessctl get`
brightness=`awk -M -v PREC=7 "BEGIN {print $b / 255 * 100}"`
dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-low.svg -r 2593 -u normal
}

up() {
brightnessctl set +5%
b=`brightnessctl get`
brightness=`awk -M -v PREC=7 "BEGIN {print $b / 255 * 100}"`
echo $brightness
dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-high.svg -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
