#!/bin/sh

down() {
	pamixer -u
	pamixer -d 2
	volume=$(pamixer --get-volume)
	[$volume -gt 0 ] && volume=`expr $volume`  
	dunstify -t 1000 -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i ~/.config/dunst/assets/ui/volume_low.png -r 2593 -u normal
	canberra-gtk-play -i audio-volume-change -d "changevolume"
}

up() {
	pamixer -u
	pamixer -i 2
	volume=$(pamixer --get-volume)
	[ $volume -lt 1000 ] && volume=`expr $volume`  
	dunstify -t 1000 -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i ~/.config/dunst/assets/ui/volume_high.png -r 2593 -u normal
	canberra-gtk-play -i audio-volume-change -d "changevolume"
}

mute() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
  dunstify -t 1000 -a "VOLUME" "UNMUTED" -i ~/.config/dunst/assets/ui/volume_high.svg -r 2593 -u normal
else 
  pamixer -m
  dunstify -t 1000 -a "VOLUME" "MUTED" -i ~/.config/dunst/assets/ui/volume_muted.svg -r 2593 -u normal
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
