#!/bin/bash

set -euo pipefail

notify() {
    local asset=""
    local volume=""
    while test $# -ne 0
    do
        case "$1" in
            -t|--text)
                shift
                local text="$1"
                ;;

            -a|--asset)
                shift
                local dir="$HOME/.config/dunst/assets/ui/"
                asset=$(find "$dir" -name "$1*")
                [[ -f "$asset" ]] || return 2;
                ;;
            -v|--volume)
                shift
                volume="$1"
                ;;
        esac
        shift
    done

    [[ -z "${text}" ]] && return 3
    hint_opt=${volume:+"-h int:value:$volume"}
    image_opt=${asset:+"-i $asset"}

    dunstify -t 1000 \
             -a "VOLUME" "$text" \
             ${hint_opt} \
             ${image_opt} \
             -u normal \
             -r 42
}

play_sound() {
    canberra-gtk-play -i audio-volume-change -d "changevolume"
}

mute() {
    pamixer -m
}

unmute() {
    pamixer -u
}

volume() {
    pamixer --get-volume
}

down() {
    unmute
    pamixer -d 2

    local v
    v=$(volume)

    notify -t "Decreasing to $v%" -v "$v" -a volume_low
    play_sound
}

up() {
    unmute
    pamixer -i 2

    local v
    v=$(volume)

    notify -t "Increasing to $v%" -v "$v" -a volume_high
    play_sound
}

toggle_mute() {
    if "$(pamixer --get-mute)";
    then
        unmute
        notify -t UNMUTED -a volume_high
    else 
        mute
        notify -t MUTED -a volume_muted
    fi
}

case "$1" in
  up) up;;
  down) down;;
  toggle) toggle_mute;;
esac
