""" TODO!
"
" - how to :find in case-insentive manner
"
" - how to ignore some files/directories in :find Maybe a better way is to
"   exclude files which should be ignored from working directory. E.g. do
"   something like this:
"   	project-workspace/
"        |--- project/
"        |--- build/
"
"   Although, some programs like clangd will put its files into .cache/ or
"   elsewhere in project/.
"
"   NOTE! :find will ignore hidden files (at least on linux). So, another way
"   is to `mv build/ .bulid/`.
"
" - How to make :find fuzzy. Pretty like :buffer.
" - In case where writing ':find filename' and pressing <Tab> will
"   autocomplete the only match, I want to just write ':find filename' and
"   press <CR> and get autcompleted 'filename.txt' or
"   'anyprefix_filename_anypostfix' opened
"

""" DONT POLLUTE MY HOME, PLEASE...

if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" | endif
if empty($XDG_STATE_HOME)  | let $XDG_STATE_HOME  = $HOME."/.local/state" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME . "/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p', 0700)
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p', 0700)
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p', 0700)
set viminfofile=$XDG_STATE_HOME/vim/viminfo


""" SOME BASIC STUFF:

" use K (shift + k) to find help about anything below
set nocompatible
set nowrap
set undofile
set number
set scrolloff=7
set sidescroll=1
set sidescrolloff=15
set shiftwidth=4
set tabstop=4

set ignorecase
set smartcase
set hlsearch
set incsearch

" HACK! https://stackoverflow.com/questions/79898428/map-esc-to-vim-command-in-vimrc
func! EscSetup(timerid)
    nnoremap <silent> <Esc> :nohl<CR>
endfunc
autocmd VimEnter * call timer_start(100, 'EscSetup')

syntax enable
filetype plugin on
filetype indent on

" 0 -> blinking block.
" 1 -> blinking block (default).
" 2 -> steady block.
" 3 -> blinking underline.
" 4 -> steady underline.
" 5 -> blinking bar (xterm).
" 6 -> steady bar (xterm).
"
let &t_SI = "\e[6 q"    " insert
let &t_SR = "\e[4 q"    " replace
let &t_EI = "\e[2 q"    " normal


""" FINDING FILES:

set path+=**
nnoremap <silent> <Space>f :FZF<CR>


""" PACKAGES:

packadd! editorconfig


""" FILE BROWSING:

let g:netrw_banner=0    "
let g:netrw_liststyle=3 " tree view

