#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

export PATH="${PATH}:${HOME}/.local/bin"

complete -F _command doas

PS1='[\u@\h \W]\$ '
neofetch
